<a href="https://colab.research.google.com/github/SiddSai/Learning-PyTorch/blob/main/DeepLearningWithPytorch_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [6]:
# Reshape Data: Reshape and View

my_torch = my_torch.reshape(5, 2)
my_torch

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [11]:
# Reshape if we do not know # items. Use -1
my_torch2 = torch.arange(15)

In [15]:
my_torch2 = my_torch2.reshape(-1, 5)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [22]:
# Try view

my_torch3 = torch.arange(15)
my_torch3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
my_torch4 = my_torch3.view(3, 5)
my_torch4

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [25]:
# with reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [28]:
my_torch5[1] = 4141
print(my_torch5)
print(my_torch6)

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])
tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])


In [31]:
# Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# Grab a specific item
my_torch7[7]

tensor(7)

In [34]:
# Grab a slice
my_torch8 = my_torch7.reshape(5, 2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [35]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [36]:
# Return column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])