<a href="https://colab.research.google.com/github/SiddSai/Learning-PyTorch/blob/main/DeepLearningWithPytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Neural Network:
- Way to learn with machines
- Similar to brain with neurons (how they developed)
- Starts in input layer
- Ends in input layer
- Learning happens in the layers of neurons
- Layers have different weights (probablistic weights)
- Different types of NN's have different learning methods through neurons
- Workflow: Input -> Learning -> Output


In [ ]:
import torch
import numpy as np

Tensor:


* Like a numpy array or python list
* Machine Learning: numpy list
* Deep Learning: tensors (more powerful/scaled for deep learning)
* Multi-dimensional matrix containing elements of a single data type
* Default data type: float32




In [ ]:
### Lists

# Test
my_list = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(my_list)

[[1, 2, 3, 4], [5, 6, 7, 8]]


In [ ]:
### Numpy Arrays

# Test
np1 = np.random.rand(3, 4)
print(np1)

# Check data type
print(np1.dtype)



[[0.29454191 0.34179865 0.62500541 0.57058967]
 [0.48873997 0.86706771 0.52256015 0.73414769]
 [0.0858894  0.49848642 0.73556086 0.01476674]]
float64


In [ ]:
### Tensors

# 3D
tensor_2d = torch.randn(3, 4)
print(tensor_2d)
tensor_2d.dtype

tensor([[-1.9393,  0.5018, -0.2700,  0.9935],
        [-1.2486,  0.5211, -0.9323,  1.6569],
        [-0.8645,  0.6275, -0.6714, -0.5695]])


torch.float32

In [ ]:
# 3D
tensors_3d = torch.zeros(2, 3, 4)
print(tensors_3d)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [ ]:
# Convert numpy array to tensor

np_to_tensor = torch.tensor(np1)
print(np_to_tensor)

tensor([[0.2945, 0.3418, 0.6250, 0.5706],
        [0.4887, 0.8671, 0.5226, 0.7341],
        [0.0859, 0.4985, 0.7356, 0.0148]], dtype=torch.float64)
